/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.learn.minimcdonalds;

public class App {

    public static void main(String[] args) {
        
    }
    
    // TODO: setup Amazon SQS client
}
